<a href="https://colab.research.google.com/github/rafayel404/Pandas/blob/main/Pandas_4_group_by.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
movies = pd.read_csv('/content/imdb-top-1000.csv')

In [5]:
movies.sample(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
511,The Bourne Identity,2002,119,Action,7.9,Doug Liman,Franka Potente,508771,121661683.0,68.0
764,Ex Machina,2014,108,Drama,7.7,Alex Garland,Alicia Vikander,474141,25442958.0,78.0
157,Der Untergang,2004,156,Biography,8.2,Oliver Hirschbiegel,Bruno Ganz,331308,5509040.0,82.0
78,Dr. Strangelove or: How I Learned to Stop Worr...,1964,95,Comedy,8.4,Stanley Kubrick,Peter Sellers,450474,275902.0,97.0
630,Adams æbler,2005,94,Comedy,7.8,Anders Thomas Jensen,Ulrich Thomsen,45717,1305.0,51.0

In [6]:
genres=movies.groupby('Genre')

In [7]:
genres.sum(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [8]:
genres.min(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes        Gross  Metascore
Genre
Action          45          7.6        25312       3296.0       33.0
Adventure       88          7.6        29999      61001.0       41.0
Animation       71          7.6        25229     128985.0       61.0
Biography       93          7.6        27254      21877.0       48.0
Comedy          68          7.6        26337       1305.0       45.0
Crime           80          7.6        27712       6013.0       47.0
Drama           64          7.6        25088       3600.0       28.0
Family         100          7.8       178731    4000000.0       67.0
Fantasy         76          7.9        57428  337574718.0        NaN
Film-Noir      100          7.8        59556     449191.0       94.0
Horror          71          7.6        27007      89029.0       46.0
Mystery         96          7.6        33982    1035953.0       52.0
Thriller       108          7.8        27733   17550741.0       81.0
Western        132          7.8        65659    5321508.0       69.0

In [9]:
genres.median(numeric_only=True)

           Runtime  IMDB_Rating  No_of_Votes        Gross  Metascore
Genre
Action       127.5          7.9     275497.0  103858027.5       74.0
Adventure    127.0          7.9     236060.5   57160627.0       80.5
Animation     99.5          7.9     169246.0  145219819.0       82.0
Biography    129.0          7.9     188676.5   51710054.0       76.0
Comedy       106.0          7.9      88511.0   19516000.0       79.0
Crime        122.0          8.0     142107.0   16290476.0       77.0
Drama        121.0          8.0      86525.0   18500194.0       82.0
Family       107.5          7.8     275610.5  219555277.0       79.0
Fantasy       85.0          8.0      73111.0  391363348.0        NaN
Film-Noir    104.0          8.0     148928.0    2108060.0       96.0
Horror       103.0          7.8     362393.0   56000369.0       87.0
Mystery      117.5          8.0     159514.0   31154590.0       77.0
Thriller     108.0          7.8      27733.0   17550741.0       81.0
Western      148.0          8.4     267808.0   10550000.0       77.0

In [10]:
# find the top 3 genres by total earning
genres.sum(numeric_only=True)['Gross'].sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [11]:
genres.Gross.sum().sort_values(ascending=False).head(3) # This is more effiecient. I don't have to sum all the column here.

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [12]:
# find the genre with highest avg IMDB rating
genres.IMDB_Rating.mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [13]:
# find director with most popularity
movies.groupby('Director').No_of_Votes.sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [14]:
# find number of movies done by each actor
# movies['Star1'].value_counts()

movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
                     ..
Gérard Jugnot         1
Günes Sensoy          1
Haluk Bilginer        1
Harriet Andersson     1
Graham Chapman        1
Name: Series_Title, Length: 660, dtype: int64

In [15]:
# GroupBy Attributes and Methods



# groups
# describe
# sample
# nunique

In [16]:
len(genres) # find total number of groups -> len

14

In [17]:
movies.Genre.nunique()

14

In [18]:
# find items in each group -> size

genres.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [19]:
movies.value_counts('Genre')

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Family         2
Fantasy        2
Thriller       1
Name: count, dtype: int64

In [20]:
# first()/last() -> nth item
genres.first() # first row of every group

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [21]:
genres.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [34]:
genres=movies.groupby('Genre')
genres.nth(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
5,The Lord of the Rings: The Return of the King,2003,201,Action,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
9,Fight Club,1999,139,Drama,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
15,Goodfellas,1990,146,Biography,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
47,Back to the Future,1985,116,Adventure,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0

In [23]:

# get_group -> vs filtering
#movies[movies['Genre']=='Horror']

genres.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [24]:
genres.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [25]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [26]:
genres.sample() # give me a sample from every group.

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
898,Dawn of the Planet of the Apes,2014,130,Action,7.6,Matt Reeves,Gary Oldman,411599,208545589.0,79.0
329,The Martian,2015,144,Adventure,8.0,Ridley Scott,Matt Damon,760094,228433663.0,80.0
761,Toki o kakeru shôjo,2006,98,Animation,7.7,Mamoru Hosoda,Riisa Naka,60368,329525432.0,NaN
416,Dog Day Afternoon,1975,125,Biography,8.0,Sidney Lumet,Al Pacino,235652,50000000.0,86.0
732,Me and Earl and the Dying Girl,2015,105,Comedy,7.7,Alfonso Gomez-Rejon,Thomas Mann,123210,6743776.0,74.0
520,True Romance,1993,119,Crime,7.9,Tony Scott,Christian Slater,206918,12281500.0,59.0
196,Pink,2016,136,Drama,8.1,Aniruddha Roy Chowdhury,Taapsee Pannu,39216,1241223.0,NaN
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
691,The Outlaw Josey Wales,1976,135,Western,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [27]:
genres.sample(2,replace=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
982,Mad Max 2,1981,96,Action,7.6,George Miller,Mel Gibson,166588,12465371.0,77.0
325,Bajrangi Bhaijaan,2015,163,Action,8.0,Kabir Khan,Salman Khan,72245,8178001.0,NaN
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
61,Coco,2017,105,Animation,8.4,Lee Unkrich,Adrian Molina,384171,209726015.0,81.0
651,Shrek,2001,90,Animation,7.8,Andrew Adamson,Vicky Jenson,613941,267665011.0,84.0
810,Shine,1996,105,Biography,7.7,Scott Hicks,Geoffrey Rush,51350,35811509.0,87.0
173,Raging Bull,1980,129,Biography,8.2,Martin Scorsese,Robert De Niro,321860,23383987.0,89.0
208,OMG: Oh My God!,2012,125,Comedy,8.1,Umesh Shukla,Paresh Rawal,51739,923221.0,NaN
472,Sing Street,2016,106,Comedy,7.9,John Carney,Ferdia Walsh-Peelo,85109,3237118.0,79.0
444,Les diaboliques,1955,117,Crime,8.0,Henri-Georges Clouzot,Simone Signoret,61503,67939432.0,NaN
87,Drishyam,2013,160,Crime,8.3,Jeethu Joseph,Mohanlal,30722,11339376.0,NaN
504,Gegen die Wand,2004,121,Drama,7.9,Fatih Akin,Birol Ünel,51325,213063755.0,78.0
296,Ivanovo detstvo,1962,95,Drama,8.1,Andrei Tarkovsky,Eduard Abalov,31728,388466313.0,NaN
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

In [28]:
genres.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [29]:
# agg
genres.agg(
    {
         'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Gross':'sum',
         'Metascore':'std'

    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10  12.421252
Adventure  134.111111     7.937500     22576163  9.496922e+09  12.345393
Animation   99.585366     7.930488     21978630  1.463147e+10   8.813646
Biography  136.022727     7.938636     24006844  8.276358e+09  11.028187
Comedy     112.129032     7.901290     27620327  1.566387e+10  11.829160
Crime      126.392523     8.016822     33533615  8.452632e+09  13.099102
Drama      124.737024     7.957439     61367304  3.540997e+10  12.744687
Family     107.500000     7.800000       551221  4.391106e+08  16.970563
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08   1.527525
Horror     102.090909     7.909091      3742556  1.034649e+09  15.362291
Mystery    119.083333     7.975000      4203004  1.256417e+09  18.604435
Thriller   108.000000     7.800000        27733  1.755074e+07        NaN
Western    148.250000     8.350000      1289665  5.822151e+07   9.032349

In [30]:
# passing list
# genres.agg(['min','max','sum'])

In [31]:
movies.groupby('Genre')[['IMDB_Rating', 'No_of_Votes', 'Gross']].agg(['mean', 'max', 'min'])

          IMDB_Rating              No_of_Votes                          Gross  \
                 mean  max  min           mean      max     min          mean
Genre
Action       7.949419  9.0  7.6  420246.581395  2303232   25312  1.897224e+08
Adventure    7.937500  8.6  7.6  313557.819444  1512360   29999  1.319017e+08
Animation    7.930488  8.6  7.6  268032.073171   999790   25229  1.784326e+08
Biography    7.938636  8.9  7.6  272805.045455  1213505   27254  9.404952e+07
Comedy       7.901290  8.6  7.6  178195.658065   939631   26337  1.010572e+08
Crime        8.016822  9.2  7.6  313398.271028  1826188   27712  7.899656e+07
Drama        7.957439  9.3  7.6  212343.612457  2343110   25088  1.225259e+08
Family       7.800000  7.8  7.8  275610.500000   372490  178731  2.195553e+08
Fantasy      8.000000  8.1  7.9   73111.000000    88794   57428  3.913633e+08
Film-Noir    7.966667  8.1  7.8  122405.000000   158731   59556  4.197018e+07
Horror       7.909091  8.5  7.6  340232.363636   787806   27007  9.405902e+07
Mystery      7.975000  8.4  7.6  350250.333333  1129894   33982  1.047014e+08
Thriller     7.800000  7.8  7.8   27733.000000    27733   27733  1.755074e+07
Western      8.350000  8.8  7.8  322416.250000   688390   65659  1.455538e+07


                   max          min
Genre
Action     936662225.0       3296.0
Adventure  874211619.0      61001.0
Animation  873839108.0     128985.0
Biography  753585104.0      21877.0
Comedy     886752933.0       1305.0
Crime      790482117.0       6013.0
Drama      924558264.0       3600.0
Family     435110554.0    4000000.0
Fantasy    445151978.0  337574718.0
Film-Noir  123353292.0     449191.0
Horror     298791505.0      89029.0
Mystery    474203697.0    1035953.0
Thriller    17550741.0   17550741.0
Western     31800000.0    5321508.0

In [32]:
# Adding both the syntax
genres.agg(
    {
        'Runtime':['min','mean'],
        'IMDB_Rating':'mean',
        'No_of_Votes':['sum','max'],
        'Gross':'sum',
        'Metascore':'min'
    }
)

          Runtime             IMDB_Rating No_of_Votes                  Gross  \
              min        mean        mean         sum      max           sum
Genre
Action         45  129.046512    7.949419    72282412  2303232  3.263226e+10
Adventure      88  134.111111    7.937500    22576163  1512360  9.496922e+09
Animation      71   99.585366    7.930488    21978630   999790  1.463147e+10
Biography      93  136.022727    7.938636    24006844  1213505  8.276358e+09
Comedy         68  112.129032    7.901290    27620327   939631  1.566387e+10
Crime          80  126.392523    8.016822    33533615  1826188  8.452632e+09
Drama          64  124.737024    7.957439    61367304  2343110  3.540997e+10
Family        100  107.500000    7.800000      551221   372490  4.391106e+08
Fantasy        76   85.000000    8.000000      146222    88794  7.827267e+08
Film-Noir     100  104.000000    7.966667      367215   158731  1.259105e+08
Horror         71  102.090909    7.909091     3742556   787806  1.034649e+09
Mystery        96  119.083333    7.975000     4203004  1129894  1.256417e+09
Thriller      108  108.000000    7.800000       27733    27733  1.755074e+07
Western       132  148.250000    8.350000     1289665   688390  5.822151e+07

          Metascore
                min
Genre
Action         33.0
Adventure      41.0
Animation      61.0
Biography      48.0
Comedy         45.0
Crime          47.0
Drama          28.0
Family         67.0
Fantasy         NaN
Film-Noir      94.0
Horror         46.0
Mystery        52.0
Thriller       81.0
Western        69.0

In [33]:
# looping on groups
# data is every group
# append is depriciated in pandas . We should use pd.concat

df = pd.DataFrame(columns=movies.columns)
for group,data in genres:
  df=df.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

df

AttributeError: 'DataFrame' object has no attribute 'append'

In [35]:
# List to hold the max IMDB_Rating data for each group
max_rating_movies = []

# Loop through each group and filter the row with the max IMDB_Rating
for group, data in genres:
    max_rating_movies.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

# Concatenate all results at once
df = pd.concat(max_rating_movies, ignore_index=True)

# Display the result
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [39]:
# maximum imdb reating of every group
for group,data in genres:
   print(data['IMDB_Rating'].max())

9.0
8.6
8.6
8.9
8.6
9.2
9.3
7.8
8.1
8.1
8.5
8.4
7.8
8.8

In [48]:
l=[]
for group,data in genres:
   print(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

      Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
2  The Dark Knight          2008      152  Action          9.0

            Director           Star1  No_of_Votes        Gross  Metascore
2  Christopher Nolan  Christian Bale      2303232  534858444.0       84.0
    Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
21  Interstellar          2014      169  Adventure          8.6

             Director                Star1  No_of_Votes        Gross  \
21  Christopher Nolan  Matthew McConaughey      1512360  188020017.0

    Metascore
21       74.0
                     Series_Title Released_Year  Runtime      Genre  \
23  Sen to Chihiro no kamikakushi          2001      125  Animation

    IMDB_Rating        Director          Star1  No_of_Votes       Gross  \
23          8.6  Hayao Miyazaki  Daveigh Chase       651376  10055859.0

    Metascore
23       96.0
       Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7  Schindler's List          1993      195  Biography          8.9

           Director        Star1  No_of_Votes       Gross  Metascore
7  Steven Spielberg  Liam Neeson      1213505  96898818.0       94.0
       Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
19     Gisaengchung          2019      132  Comedy          8.6
26  La vita è bella          1997      116  Comedy          8.6

           Director            Star1  No_of_Votes       Gross  Metascore
19     Bong Joon Ho     Kang-ho Song       552778  53367844.0       96.0
26  Roberto Benigni  Roberto Benigni       623629  57598247.0       59.0
    Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1  The Godfather          1972      175  Crime          9.2

               Director          Star1  No_of_Votes        Gross  Metascore
1  Francis Ford Coppola  Marlon Brando      1620367  134966411.0      100.0
               Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
0  The Shawshank Redemption          1994      142  Drama          9.3

         Director        Star1  No_of_Votes       Gross  Metascore
0  Frank Darabont  Tim Robbins      2343110  28341469.0       80.0
                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0

     Metascore
321        NaN
      Series_Title Released_Year  Runtime      Genre  IMDB_Rating    Director  \
309  The Third Man          1949      104  Film-Noir          8.1  Carol Reed

            Star1  No_of_Votes     Gross  Metascore
309  Orson Welles       158731  449191.0       97.0
   Series_Title Released_Year  Runtime   Genre  IMDB_Rating          Director  \
49       Psycho          1960      109  Horror          8.5  Alfred Hitchcock

              Star1  No_of_Votes       Gross  Metascore
49  Anthony Perkins       604211  32000000.0       97.0
   Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69      Memento          2000      113  Mystery          8.4
81  Rear Window          1954      112  Mystery          8.4

             Director          Star1  No_of_Votes       Gross  Metascore
69  Christopher Nolan     Guy Pearce      1125712  25544867.0       80.0
81   Alfred Hitchcock  James Stewart       444074  36764313.0      100.0
        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore
700  Terence Young  Audrey Hepburn        27733  17550741.0       81.0
                       Series_Title Released_Year  Runtime    Genre  \
12  Il buono, il brutto, il cattivo          1966      161  Western

    IMDB_Rating      Director           Star1  No_of_Votes      Gross  \
12          8.8  Sergio Leone  Clint Eastwood       688390  6100000.0

    Metascore
12       90.0

In [52]:
l=[]
for group,data in genres:
   l.append(data[data['IMDB_Rating'] == data['IMDB_Rating'].max()])

k=pd.concat(l,ignore_index=False)
k

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [53]:
# split (apply) combine
# apply -> builtin function

genres.apply(min)

<ipython-input-53-05c828fb38c6>:4: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
<ipython-input-53-05c828fb38c6>:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,1925,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [60]:
# find number of movies starting with A for each group

def foo(group):
  return group['Series_Title'].str.startswith('A').sum()

In [61]:
genres.apply(foo)

<ipython-input-61-13dfab5f8480>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(foo)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [63]:
# find ranking of each movie in the group according to IMDB score

def rank_movie(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [64]:
genres.apply(rank_movie)

<ipython-input-64-ba7147e2ecdc>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [65]:
# find normalized IMDB rating group wise

def normal(group):
  group['norm_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

genres.apply(normal)

<ipython-input-65-7e237221fbce>:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              norm_rating
Genre
Action   2       1.000000
         5       0.928571
         8       0.857143
         10      0.857143
         13      0.785714
...                   ...
Thriller 700          NaN
Western  12      1.000000
         48      0.700000
         115     0.500000
         691     0.000000

[1000 rows x 11 columns]

In [66]:
# groupby on multiple cols
duo = movies.groupby(['Director','Star1'])
duo
# size
duo.size()
# get_group
duo.get_group(('Aamir Khan','Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [67]:
# find the most earning actor->director combo
duo['Gross'].sum().sort_values(ascending=False).head(5)

Director           Star1
Akira Kurosawa     Toshirô Mifune    2.999877e+09
Anthony Russo      Joe Russo         2.205039e+09
Billy Wilder       William Holden    1.286779e+09
Christopher Nolan  Christian Bale    1.242940e+09
Werner Herzog      Klaus Kinski      1.124605e+09
Name: Gross, dtype: float64

In [68]:
# find the best(in-terms of metascore(avg)) actor->genre combo
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False).head(5)

               Star1      Genre  Metascore
606    Peter O'Toole  Adventure      100.0
590     Orson Welles      Drama      100.0
77       Bertil Guve      Drama      100.0
230   Ellar Coltrane      Drama      100.0
329  Humphrey Bogart      Drama      100.0

In [71]:
type(movies.groupby(['Star1','Genre'])['Metascore'].mean())

pandas.core.series.Series

In [72]:
#  by using reset_index() we transformed this series into a dataframe

In [74]:
# agg on multiple groupby
duo[['Gross','Metascore'	]].agg(['min','max','mean'])

                                          Gross                            \
                                            min          max         mean
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0    1223869.0
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0  853090410.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0    2199675.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0  218428303.0
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0    1122527.0
...                                         ...          ...          ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0     144501.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0    3108485.0
                    Vijay Varma       5566534.0    5566534.0    5566534.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0  196206077.0

                                   Metascore
                                         min   max  mean
Director            Star1
Aamir Khan          Amole Gupte          NaN   NaN   NaN
Aaron Sorkin        Eddie Redmayne      77.0  77.0  77.0
Abdellatif Kechiche Léa Seydoux         89.0  89.0  89.0
Abhishek Chaubey    Shahid Kapoor        NaN   NaN   NaN
Abhishek Kapoor     Amit Sadh           40.0  40.0  40.0
...                                      ...   ...   ...
Zaza Urushadze      Lembit Ulfsak       73.0  73.0  73.0
Zoya Akhtar         Hrithik Roshan       NaN   NaN   NaN
                    Vijay Varma         65.0  65.0  65.0
Çagan Irmak         Çetin Tekindor       NaN   NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz           NaN   NaN   NaN

[898 rows x 6 columns]

In [77]:
pd.set_option('display.max_rows', None)

In [78]:


ipl = pd.read_csv('/content/deliveries.csv')
ipl.sample(5)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
14916,64,1,Deccan Chargers,Kolkata Knight Riders,19,3,SB Bangar,RP Singh,M Kartik,0,...,0,0,0,0,0,0,0,SB Bangar,caught,WP Saha
81949,347,2,Kolkata Knight Riders,Chennai Super Kings,9,6,JH Kallis,G Gambhir,RA Jadeja,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
127813,539,1,Delhi Daredevils,Mumbai Indians,1,4,JP Duminy,SS Iyer,MJ McClenaghan,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
164084,7951,1,Kolkata Knight Riders,Rajasthan Royals,11,5,S Gill,KD Karthik,B Laughlin,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
82454,349,2,Delhi Daredevils,Rajasthan Royals,12,5,LRPL Taylor,V Sehwag,GB Hogg,0,...,0,0,0,0,0,0,0,LRPL Taylor,caught,SP Goswami

In [79]:
# find the top 10 batsman in terms of runs
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [80]:
six = ipl[ipl['batsman_runs'] == 6]

six.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(5)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
Name: batsman, dtype: int64

In [81]:
# find batsman with most number of 4's and 6's in last 5 overs
temp_df = ipl[ipl['over'] > 15]
temp_df = temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

In [82]:
# find V Kohli's record against all teams
temp_df = ipl[ipl['batsman'] == 'V Kohli']

temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

In [83]:
# Create a function that can return the highest score of any batsman
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [84]:
def highest(batsman):
  temp_df = ipl[ipl['batsman'] == batsman]
  return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [85]:
highest('DA Warner')

np.int64(126)